{% set name = "universal-ctags" %}
{% set version = "5.9.20210214.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/universal-ctags/ctags/archive/p{{ version }}.tar.gz
  sha256: 26d9efe481a57e81195878cdb0baca730a3c4d234b9a7c4f6bf2c8def42bf42b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - libiconv
    - libxml2
    - jansson
    - libseccomp  # [linux]
    - yaml
  run_constrained:
    # Contains the same binary ctags
    - ctags <0a0

test:
  commands:
    - ctags --help

about:
  home: https://github.com/universal-ctags/ctags
  license: GPL-2.0-only
  license_file: COPYING
  summary: A maintained ctags implementation

extra:
  recipe-maintainers:
    - xhochy
