{% set name = "universal-ctags" %}
{% set version = "6.0.20230813.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/universal-ctags/ctags/archive/p{{ version }}.tar.gz
  sha256: 10fd1f3eeab7b4d3b2d43c21870e2a2d8fbe5e9f9cdabb881d3081a6176665e1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - libiconv
    - libxml2
    - jansson
    - libseccomp  # [linux]
    - yaml
  run_constrained:
    # Contains the same binary ctags
    - ctags <0a0

test:
  commands:
    - ctags --help

about:
  home: https://github.com/universal-ctags/ctags
  license: GPL-2.0-only
  license_file: COPYING
  summary: A maintained ctags implementation

extra:
  recipe-maintainers:
    - xhochy
