{% set name = "universal-ctags" %}
{% set version = "6.1.20240825.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/universal-ctags/ctags/archive/p{{ version }}.tar.gz
  sha256: 4ac5f21c138a763ceb00f9cb12f0d420632f155f0a45573ed0f7d98bd516df99

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - libiconv
    - libxml2
    - jansson
    - libseccomp  # [linux]
    - yaml
  run_constrained:
    # Contains the same binary ctags
    - ctags <0a0

test:
  commands:
    - ctags --help

about:
  home: https://github.com/universal-ctags/ctags
  license: GPL-2.0-only
  license_file: COPYING
  summary: A maintained ctags implementation

extra:
  recipe-maintainers:
    - xhochy
